eval_test.go, utils.go
Hi @antonmedv,
Saw this on Golang Weekly and though it looked pretty good.  Added a PR which dereferences pointers to structs when attempting to extract a field name so that pointers to structs can be used as data alongside regular structs.  Example:
```!go
type Data struct {
X int
}
data := &Data{X: 123}
result, err := expr.Eval("X", data)
// result == 123
```
Hope you find it useful.
Thanks,
Leon
=> Added pointer dereferencing for field extraction

README.md, bench_test.go, doc.go, doc_test.go, eval.go, eval_test.go, node.go, parser.go, parser_test.go, print.go, print_test.go, type.go, type_test.go, utils.go
This commits implements more advance type checks in strict mode.
To enter strict mode set variable types with expr.Define() or
expr.With() functions.
=> Add type checks

type.go, type_test.go
Return correct type from bit, arithmetic and range operations
=> Fix type check of binary node

eval_test.go, runtime.go
Hi, I find out that while calling `getFunc(...)`, when the kind of val is `Map`, will only assume the method is provide by k-v. But even a map can have it is own method, and it will help a lot. 
For example:
```go
type ExprParams map[string]interface{}
func (e ExprParams) Max(a, b float64) float64 {
return math.Max(a, b)
}
type User struct{
Age int
}
func demo(){
expr.Eval("Max(Teacher.Age, Student.Age)",ExprParams{
"Teacher":User{Age:28},
"Student":Student{Age:8},
})
}
```
In this cases, `ExprParams` can provide default method ( like `Max`) easily.
And the implement is very simple, I hope it can improve the lib.
Thanks a lot.
PS: another question
I find that the only to calling for `getFunc(val interface{}, i interface{})`, the param `i` is both `string`, why not just change the …
=> Add support for method of map.

docs/Usage.md
I noticed the example contained a few compilation errors, related to pointers and the name of the variable used in the typecasting. Just a quick PR to update the example 😄
=> fixed visitor usage example as it had compilation errors

bench_test.go, vm/runtime.go
Adds a test with a 10mb struct passed by a pointer, it would be previously
copied on property accessed whereas now the accesses just go through the
pointer without a copy.
Previous:
Benchmark_largeStructAccess-4          200     7914350 ns/op
After:
Benchmark_largeStructAccess-4      2000000         912 ns/op
=> runtime: Don't value copy structs from pointers on property access

expr.go, expr_test.go, internal/conf/config.go
I'd like to pass around and reuse the options when compiling many expressions, but being in an  internal package makes that difficult.
=> Move conf.Option out of internal package

expr_test.go, parser/lexer/lexer.go, parser/lexer/lexer_test.go, parser/lexer/state.go, parser/lexer/token.go
Thir PR should fix the handling of extra space `(U+0020)` between multi-word operators (eg. `not in`). I had another hacky solution though where I initially thought to sanitize the input in `parser/parser.go` in the `Parse` function with something like:
```go
func sanitize(input string) string {
return strings.Join(strings.Fields(strings.TrimSpace(input)), " ")
}
```
But again this is a bad idea.
Now the implementation is generic enough and should help to parse other multi-word operators as well. @antonmedv does it look good to you?
Also did some nit fixes:
- Remove the unused state from lexer struct
- Fix formatting
- Use the type Kind for Number, String, Operator, Bracket, EOF
Fixes #123
=> Fix handling of space(s) in between operator

expr_test.go, optimizer/const_range.go, vm/runtime.go
For double dot range i.e., `a..b` where `a` and `b` are inclusive when ranging from `a` to `b`. Therefore every element x in the range must satisfy `a <= x && x <= b`
Previously, it used to panic because, for `a..b`, `a` is considered minimum and `b` is considered maximum which results in negative size when allocating memory for slice using `make`. Ref:
**file**: _optimizer/const_range.go_ 
```go
size := max.Value - min.Value + 1
...
...
value := make([]int, size)
``` 
So, for invalid inputs where a > b, it panics. Similar problem is there in `vm/runtime.go`'s `makeRange` function as well.
Changing it in the optimizer and makeRange seems apt to me, but I figured it could be handled in `checker/checker.go` and cry the error out loud that the expression is not correct, but it didn't feel …
=> Fix double dot range for invalid input

ast/node.go, checker/checker.go, cmd/exe/dot.go, compiler/compiler.go, expr_test.go, parser/lexer/lexer_test.go, parser/lexer/state.go, parser/parser.go, parser/parser_test.go, vm/opcodes.go, vm/program.go, vm/runtime.go, vm/vm.go
Takes care of #147 
Only thing this doesn't work on is when the env struct is predefined before compiling due to `OpEqualString` and `OpEqualInt` optimizations doing type casts.
Not completely happy with the way it's implemented, but it was the easiest to do without changing much core code.
=> Add nil safe operator

parser/lexer/lexer.go, parser/lexer/lexer_test.go, parser/parser_test.go
`acceptWord` finds the substring `word`, but does not look at the following rune. As a result, `not in_var` is interpreted as Operator(`not in`) and Identifier(`_var`)
=> acceptWord checks the rune after word

checker/checker.go, docs/Custom-Functions.md, docs/Getting-Started.md, docs/README.md, vm/vm.go, vm/vm_test.go
Also provide initial documentation on using and providing functions.
=> Add ability to return errors from custom functions.

checker/checker.go, checker/checker_test.go
After implementing an ast.Visitor (and using expr.Patch) which replaced some nodes with a ConstantNode, I was getting panics from checker.Check, as it didn't expect a ConstantNode, but this simple patch fixes that.
=> Add support for ConstantNode in checker

docs/Custom-Functions.md
As mentioned in https://github.com/antonmedv/expr/issues/198 example for "Returning errors" documentation had invalid return value.
=> docs: fix invalid return value in "Returning errors" example.

expr_test.go, optimizer/const_expr.go
Fixes https://github.com/antonmedv/expr/issues/238
If the custom func returns a non-nil error, that same error is returned from `expr.Compile` function.  
This mirrors the existing behavior for this in `expr.Run`.
Related context: https://github.com/antonmedv/expr/pull/159#issuecomment-769761579
=> fix ConstExpr to handle custom functions returning error

vm/vm.go
Currently, `memory` field is not reset when the `vm` is reused, and the value of `memory` will keep increasing if using array operation like `filter`, which makes it eventually exceed the `MemoryBudget` limit.
This commit fixed this issue and allow to reuse `vm` for the programs which contains some specific operations that increase the value of `memory`.
=> fix: reset vm.memory to reuse vm

checker/checker.go, checker/checker_test.go, checker/types.go, expr_test.go, file/source_test.go, vm/helpers.go, vm/vm_test.go
This should resolve the following issues. 
#73 
#203
#227
Before starting this PR, I attempted to add support for time operators, but ended up with an impossible state b/c I cannot support `interface{} -OP- interface{}` without losing the built-in functionality of the operators. The only option I could see was to copy/paste/extend [/vm/helpers.go](https://github.com/antonmedv/expr/blob/master/vm/helpers.go). 
I decided to search the issues and found that others have run into this too. 
---- 
With this PR, the operators `==, >=, <=, <, >` are included by default allowing users to compare `time.Time` instances, returning  bool. 
The `+` operator adds a `time.Duration` to `time.Time`, returning `time.Time`
The `-` operator returns a duration representing the diff between two `time.Time` …
=> Adds support for common operators for time.Time

expr_test.go, vm/runtime/generate/main.go, vm/runtime/helpers.go
Fixes #270
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Added all possible `/` tests for different types, and it's working as expected now. Also I had to add `runtime.ToFloat64()` for `OpDivide`, otherwise it rounds up the value and converts `float32`. For example:
```diff
- float32(0.96039605)
+ float64(0.9603960514068604)
```
`-` is wrong, `+` is correct value (with `runtime.ToFloat64`).
cc @antonmedv
=> Fix OpDivide: change resulting type to float64

docs/Language-Definition.md, expr_test.go
This fixes the examples in the language definition and adds a few more examples to the test suite that mirror this documentation.
The first example demonstrates the inclusive-exclusive nature of the indicies.
The middle two examples demonstrate the property of `array[:i]` not overlapping with `array[i:]`.
=> Clarify examples of slice behaviour

README.md
I think that CodeDNS is a typo for CoreDNS.
=> Fix typo in CoreDNS in README

compiler/compiler_test.go, optimizer/fold.go, optimizer/optimizer_test.go
This change introduces simple boolean condition optimization when dealing with boolean `and`, `or`, and `==` expressions to help trim unnecessary AST nodes.
=> Adds simple bool condition optimization

expr_test.go, file/error.go, vm/vm.go, vm/vm_test.go
=> add  'wrap' and 'unwrap' method to hold self error

docs/Getting-Started.md
There is no member named timestamp in Message.
Added some formatting for better looks.
The output now looks like this:
```
[17 Apr 23 20:34 IST	Oh My God!
17 Apr 23 20:34 IST	How you doin?
17 Apr 23 20:34 IST	Could I be wearing any more clothes?
]
```
=> Fixed a compilation error.

ast/node.go, checker/checker.go, checker/types.go, compiler/compiler.go, compiler/compiler_test.go, expr_test.go, test/deref/deref_test.go, vm/runtime/runtime.go
=> Refactor deref

debug/go.mod, debug/go.sum, parser/lexer/state.go, parser/parser.go, parser/parser_test.go, repl/go.mod, repl/go.sum, test/pipes/pipes_test.go
```
1..9 | map(# + 1) | filter(# % 2 == 0)
```
=> Pipe operator

ast/node.go, ast/print.go, ast/visitor.go, builtin/builtin.go, builtin/builtin_test.go, checker/checker.go, checker/checker_test.go, compiler/compiler.go, expr_test.go, parser/lexer/lexer_test.go, parser/lexer/state.go, parser/parser.go, parser/parser_test.go, test/deref/deref_test.go, vm/opcodes.go, vm/program.go, vm/program_test.go, vm/vm.go
=> Add variables

docgen/docgen.go
We use the javascript editor a lot and would like too see the docgen added for the builtin types.
I have not added it for some types due to optional parameters not being supported in the docgen.Type.
=> Add docgen types for most builtin types

checker/checker.go, compiler/compiler.go, expr_test.go, test/fuzz/fuzz_test.go
Propagate uint32 arguments types in ast
fix https://github.com/antonmedv/expr/issues/432
=> Propagate uint32 arguments types in ast

docs/Language-Definition.md
Since 1.14 and 1.15 added a bunch of new operators / functions, I thought that categorizing them would help discoverability
- in particular, some of the older functions were roughly categorized (all array functions in a row for instance), but newer ones seemed to have just been added to the end of the whole list
- new categories / section headings
- String functions
- Date functions
- Number functions
- Array functions
- Map functions
- Type Conversion functions
- Miscellaneous functions (uncategorized multi-type functions)
- also consistently use `str`, `array`, `map`, `n`, `v` for the variable name when referring to a specific type
- `array` was used consistently for older functions, but not some newer ones
- `str` added to match `array`
- `n` was sometimes used for numbers or ints, but …
=> docs: categorize Language Definition functions

expr_test.go, test/deref/deref_test.go, vm/runtime/runtime.go
First commit is fixing some issue with `runtime.Deref` which is called by `OpDeref`, pointer of interface were not de-referenced.
Second commit is creating a fix for #466. This is de-referencing everything in `Fetch` before fetching the attribute. 
As discussed in the issue, one other approach could be to ensure we have a `OpDeref` operation added during the compilation phase.
=> Fix Fetch and OpDeref

parser/lexer/lexer_test.go, parser/parser.go, parser/parser_test.go
The current parser lacks support for the following numeric representations:
1. Octal literals.
2. Binary literals.
3. Hexadecimal literals with a '0X' prefix.
=> Enhance the number parser to include support for parsing hexadecimal, binary, and octal literals.

checker/checker_test.go, checker/types.go, expr_test.go, test/mock/mock.go
Here's a fix for a case I ran into in practice - the checker panics on a valid input:
expression: 
```go
(Embed).EmbedPointerEmbedInt > 0
```
environment: 
```go
type Env struct {
Embed
}
type Embed struct {
*EmbedPointerEmbed
}
type EmbedPointerEmbed struct {
EmbedPointerEmbedInt int
}
```
crash:
```
panic: reflect: NumField of non-struct type *mock.EmbedPointerEmbed [recovered]
panic: reflect: NumField of non-struct type *mock.EmbedPointerEmbed
```
The fix in this PR is to dereference embedded fields until they stop being pointers (see diff in checker/types.go).
=> Fix: checker panic on embedded pointer to struct field

checker/types.go
The `for` loop from #500 is unnecessary. It doesn't break anything but it does cause an useless extra comparison after the first iteration if the loop is entered. This PR replaces it with an `if`.
I hadn't realized before that the embedded struct will never have a multi-level pointer type: you can't directly embed a `**struct` field and if the field is in a doubly-nested struct, that will take two recursion levels of `fetchField` to reach, with a `*struct` type each time.
=> replace unnecessary loop introduced in #500 with an if stmt

parser/lexer/lexer.go, parser/lexer/lexer_test.go, parser/lexer/state.go, parser/parser_test.go
The current parser lacks support for raw string literals
=> Incorporate support for raw string literals

builtin/builtin_test.go, checker/checker.go, conf/config.go, parser/lexer/lexer_test.go, parser/lexer/state.go, parser/parser.go, parser/parser_test.go
=> Allow to override builtins

.github/workflows/test.yml, compiler/compiler.go, expr_test.go, vm/program.go, vm/vm.go, vm/vm_test.go
=> Fix race cond in variabels

builtin/builtin.go, builtin/function.go, checker/checker.go, checker/checker_test.go, checker/types.go, patcher/with_context_test.go
=> Fix context patcher

compiler/compiler.go, compiler/compiler_test.go
Resolving https://github.com/expr-lang/expr/issues/26
=> Optimize jumps

expr_test.go, parser/parser.go, parser/parser_test.go
Resolving https://github.com/expr-lang/expr/issues/547
=> Add optional array access like `foo?.[42]`

conf/operators.go, expr_test.go
Hi there,
Firstly, thank you for your work! 
Secondly, let me explain the context of the PR :) 
While trying to get decimals and `expr` I encountered the following issue. When an operation is overloaded and its result becomes the object of another overloaded operation, it causes a compilation error.
**Example:**
Given
```go
package main
import (
"fmt"
"github.com/expr-lang/expr"
"github.com/shopspring/decimal"
)
func main() {
code := `A + B - C`
type Env struct {
A, B, C   decimal.Decimal
Sub       func(a, b decimal.Decimal) decimal.Decimal
Add       func(a, b decimal.Decimal) decimal.Decimal
}
options := []expr.Option{
expr.Env(Env{}),
expr.Operator("+", "Add"),
expr.Operator("-", "Sub"),
}
program, err := expr.Compile(code, options...)
if err != nil {
fmt.Printf("Compile error: %v", …
```
=> Fix operator overloading

builtin/builtin.go, builtin/builtin_test.go, docs/language-definition.md
Here pull request on the https://github.com/expr-lang/expr/issues/552
=> code(builtin) - add reverse function

checker/checker.go, conf/config.go, conf/operators.go, expr.go, test/operator/operator_test.go
=> feat: Operator overload from Function

compiler/compiler_test.go, expr_test.go, parser/operator/operator.go, parser/parser.go, parser/parser_test.go
This pull request addresses issue #589.
=> Resolved 'Not' Operator Issue in Binary Node Expression

checker/checker_test.go, conf/config.go, expr_test.go
=> `expr.Operator` passes before `expr.Env` caused error

compiler/compiler.go
Whether `OpEqualInt` and `OpEqualInt` need to be applied to the operator `!=` when convert ast to bytecode, and if so, whether to consider extracting the code that handles equal into a function named `equalBinnaryNode`
=> feat: extract code for compiling equal operator

expr_test.go, optimizer/optimizer.go, optimizer/optimizer_test.go, optimizer/predicate_combination.go
Seconds attempt at implementing this:
```
all(x, x > 1) && all(x, x < 10) -> all(x, x > 1 && x < 10)
any(x, x > 1) || any(x, x < 10) -> any(x, x > 1 || x < 10)
none(x, x > 1) && none(x, x < 10) -> none(x, x > 1 || x < 10)
```
Previous one (https://github.com/expr-lang/expr/pull/555) wasn't successful and unfortunately introduced a significant bug (https://github.com/expr-lang/expr/issues/624).
This time I focused only on 3 cases: `all` with `and`, `any` with `or`, `none` with `and` and included comprehensive tests for this optimization and logical operations between `any`/`all`/`none`/`one`
=> Optimize boolean operations between all, any, none functions

patcher/with_context.go, patcher/with_context_test.go
This makes the WithContext patcher work when passing in a struct for an env that has methods that take a context.
This is a bit fiddly because we can't quite detect the difference of function vs. method on a struct, so we have to check both the first and the second param. Since it's highly unusual to pass the context as anything other than the first parameter, this should work out just fine in practice.
Fixes #600.
=> Make WithContext work for methods on env struct

expr_test.go, vm/runtime/helpers/main.go, vm/runtime/helpers[generated].go, vm/runtime/helpers_test.go
We can try to fix https://github.com/expr-lang/expr/issues/371 with nested comparison of arrays' values but I'm not sure if it's worth it to increase amount of switch-cases for such rare (imo) case.
Also, I found that expr always goes to `reflect.DeepEqual` for bools and fixed it.
=> Compare `any` arrays

builtin/builtin.go, builtin/builtin_test.go
When parsing a string into a Time using the optional timezone parameter, set the location of the Time to the timezone's location so that Format uses that timezone.
=> Preserve The Specified Timezone In Parse

expr_test.go, vm/vm.go
=> Add checks for nil before string casts in VM

internal/spew/internalunsafe_test.go, test/operator/operator_test.go
Very small pull request that doesn't change the functionality but just corrects two small spelling mistakes.
=> fix misspell

vm/vm_test.go
Add extensive test coverage for VM opcodes including:
- Basic operations (OpLoadEnv, OpTrue, OpFalse, OpNil)
- Arithmetic operations (OpNegate, OpExponent)
- String operations (OpEqualString, OpMatches)
- Collection operations (OpIn, OpLen)
- Type operations (OpCast)
- Control flow (OpThrow)
- Function calls (OpCall0-3, OpCallN)
- Index and count manipulation (OpGetIndex, OpSetIndex)
- Profiling operations (OpProfileStart, OpProfileEnd)
Also add high-level expression tests for:
- Arithmetic expressions
- String operations
- Data structure operations
- Group and sort operations
Each test case includes detailed comments and covers both success and error cases.
These tests combined with a debugger helped me navigate the VM internals significantly.
=> test: add comprehensive VM opcode tests

docs/language-definition.md, expr_test.go, parser/lexer/lexer_test.go, parser/lexer/state.go, parser/parser.go, parser/parser_test.go
If-else conditional operator added. Makes it possible to use multiline operator in if-else blocks:
```
let a = 2;
let b = 4;
if a>b {let c = Add(a, b); c } else {b+5}
```
=> add if-else conditional

.github/workflows/diff.yml, .github/workflows/fuzz.yml
At the moment CI runs fail due to:
- https://github.com/expr-lang/expr/actions/runs/13608368368/job/38042534081?pr=760
- https://github.com/expr-lang/expr/actions/runs/13608368368/job/38042534081?pr=760
This PR fixes CI workflow compatibility issues and updates dependencies:
- Pin benchstat to specific commit (884df5) compatible with Go 1.18
instead of using "latest" which now requires Go 1.23+
- Add explanatory comment about benchstat version constraints
- Upgrade actions/upload-artifact from v3 to v4 in fuzz.yml
- Upgrade github/codeql-action from v2 to v3 in fuzz.yml
These changes ensure the CI pipeline remains compatible with Go 1.18
while benefiting from the latest improvements in GitHub Actions.
Hopefully fixes CI issues for #760
=> ci: pin benchstat version and update GitHub Actions

.github/workflows/build.yml, .github/workflows/test.yml, expr_test.go, internal/difflib/difflib_test.go
Expand test coverage to newer Go versions and fix compatibility issues:
- Add Go 1.23 and 1.24 to test matrix in test.yml
- Add Go 1.24 to build matrix in build.yml
- Fix example test names to match Go conventions:
* ExampleOperator_Decimal → ExampleOperator_with_decimal
* ExampleWithTimezone → ExampleTimezone
* ExampleGetUnifiedDiffCode → ExampleGetUnifiedDiffString
* ExampleGetContextDiffCode → ExampleGetContextDiffString
* ExampleGetContextDiffString → ExampleGetContextDiffString_second
These changes maintain compatibility with Go 1.18 (as specified in go.mod) while ensuring the codebase works correctly with the latest Go versions, which enforce stricter naming conventions for example tests.
Needs #761 + rebase
=> ci: add Go 1.23/1.24 testing and fix example test names

checker/checker.go, patcher/operator_override.go, test/patch/patch_count_test.go
See issue #637
This contains the changes from pull request #658 as well. If this pull is accepted that one may be closed.
Commit https://github.com/expr-lang/expr/commit/3da85278439a5e8ef5dc0d73f321f76742e2cecc introduced repeating the patch phase for operator overloading, but also reruns all patchers any time an operator overload is patched.
This can break patchers that don't expect to be re-run over the statement multiple times. 
This patch set splits patching into two phases. First phase only patchers that don't require multiple passes are run. Second phase only patchers that require multiple passes are run.
As a side effect, it also allows any ordering between other patchers and operator overloads, where as previously if a patcher changed a nodes type it would have to be supplied as …
=> Separate patching phases for patchers that require multiple passes.

builtin/lib.go, expr_test.go, test/fuzz/fuzz_corpus.txt, test/issues/785/issue_test.go
=> fix(785): `get` to work when return is `nil`

conf/config.go, expr.go, expr_test.go, parser/parser_test.go, vm/vm.go
=> Add expr.MaxNodes() option

vm/vm.go
Currently, it's reslicing using `[0:0]` (which is equivalent to `[:0]`), but this does not clear the memory references in the underlying array, which prevents garbage collection. For instance, if:
- A VM runs a program and pushes N items to the stack
- The last item is (or contains) a pointer or reference type
- The VM is later reused, but it always pushes less than N items to the stack
Then the Nth old item will not be garbage collected because there is still a reference to it in the underlying array.
So we need to "clear the tail" of the slice before reslicing to avoid this. See these example issues:
- https://go.dev/blog/slices-intro#a-possible-gotcha
- https://go.dev/blog/generic-slice-functions#the-fix
=> Fix *vm.VM memory leak

expr_test.go, file/error.go
Fixes issue #826
Description of changes:
The problem was that lineStart was set not after the '\n' character, but directly on it, which caused lineStart to always equal lineEnd.
In addition, there was a second minor issue — the '\n' character was being counted in the column counter, which made the counter always show 1 more than it should.
=> Fix error position reporting in multiline script

checker/checker_test.go, checker/nature/utils.go, test/issues/844/issue_test.go
Fix https://github.com/expr-lang/expr/issues/844
=> Fix #844 alternative 2: do not allow access to unexported struct fields
